- hosts: picrawler
  user: pi
  become: yes

  tasks:
    - name: Install a list of packages
      apt:
        pkg:
          - git
          - python3-pip
          - libopenexr25
          - libopenexr-dev
          - vim
          - zsh
    - name: Install python packages
      pip:
        name:
          - numpy=1.21.5
          - nltk
          - vosk
          - sounddevice
    - name: Download WiringPI
      get_url:
        url: https://project-downloads.drogon.net/wiringpi-latest.deb
        dest: /tmp/wiringpi-latest.deb
    - name: Install WiringPI package
      apt:
        deb: /tmp/wiringpi-latest.deb
    - name: Download zsh installer
      get_url:
        url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
        dest: /tmp/zsh-installer.sh
        mode: '0755'
#    - name: Execute the zsh-installer.sh
#      become: true
#      become_user: 'pi'
#      shell: /tmp/zsh-installer.sh
#    - name: Remove the zsh-installer.sh
#      file: path=/tmp/zsh-installer.sh state=absent
    - name: Git checkout ezblock
      git:
        repo: 'https://github.com/ezblockcode/ezb-pi.git'
        dest: /tmp/ezb-pi
        depth: 1
    - name: Install ezblock
      shell: python install.py
      args:
        chdir: /tmp/ezb-pi/
    - name: Create a directory model directory
      file:
        path: /opt/vosk/model/
        state: directory
        mode: '0755'
    - name: Install Vosk model
      unarchive:
        src: https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip
        dest: /opt/vosk/model/
        extra_opts: [--strip-components=1]
        remote_src: yes
